service: sonatype-nexus-infra

provider: aws

resources:
  Resources:
    FileSystem:
      Type: AWS::EFS::FileSystem
      Properties:
        Encrypted: true
        FileSystemTags:
          - Key: Name
            Value: Nexus
    Vpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: '192.168.0.0/24'
        EnableDnsHostnames: true
        EnableDnsSupport: true
        Tags:
          - Key: Name
            Value: Nexus
    SecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        CidrIp: 0.0.0.0/0
        FromPort: 22
        GroupId:
          Fn::GetAtt:
            - Vpc
            - DefaultSecurityGroup
        IpProtocol: tcp
        ToPort: 22
    InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: Nexus
    InternetGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        InternetGatewayId: !Ref InternetGateway
        VpcId: !Ref Vpc
    RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        Tags:
          - Key: Name
            Value: Nexus
        VpcId: !Ref Vpc
    Route:
      Type: AWS::EC2::Route
      Properties:
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway
        RouteTableId: !Ref RouteTable
    Subnet1:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone:
          Fn::Select:
            - 0
            - Fn::GetAZs: ''
        CidrBlock: '192.168.0.0/26'
        Tags:
          - Key: Name
            Value: Nexus
        VpcId: !Ref Vpc
    Subnet1RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref Subnet1
    Subnet2:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone:
          Fn::Select:
            - 1
            - Fn::GetAZs: ''
        CidrBlock: '192.168.0.64/26'
        Tags:
          - Key: Name
            Value: Nexus
        VpcId: !Ref Vpc
    Subnet2RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref Subnet2
    MountTarget1:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId: !Ref FileSystem
        SecurityGroups:
          - Fn::GetAtt:
            - Vpc
            - DefaultSecurityGroup
        SubnetId: !Ref Subnet1
    MountTarget2:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId: !Ref FileSystem
        SecurityGroups:
          - Fn::GetAtt:
            - Vpc
            - DefaultSecurityGroup
        SubnetId: !Ref Subnet2
    EC2Role:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "ec2.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        Path: /
        Policies:
          - PolicyName: "root"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "ec2:*"
                    - "elasticfilesystem:*"
                    - "kms:*"
                  Resource: "*"
        RoleName: sonatype-nexus-role
    InstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        InstanceProfileName: Nexus
        Path: /
        Roles:
          - !Ref EC2Role
  Outputs:
    FileSystem:
      Value: !Ref FileSystem
    VpcId:
      Value: !Ref Vpc
      Export:
        Name: sonatype-nexus-vpc
    Subnet1Id:
      Value: !Ref Subnet1
      Export:
        Name: sonatype-nexus-subnet1
    Subnet2Id:
      Value: !Ref Subnet2
      Export:
        Name: sonatype-nexus-subnet2
    InstanceProfile:
      Value:
        Fn::GetAtt:
          - InstanceProfile
          - Arn
      Export:
        Name: sonatype-nexus-instanceprofile
    SecurityGroup:
      Value:
        Fn::GetAtt:
          - Vpc
          - DefaultSecurityGroup
      Export:
        Name: sonatype-nexus-securitygroup
